name: asid
channels:
  - defaults
dependencies:
  - python=3.8
  - pip:
      - pandas
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - antlr4-python3-runtime==4.9.3
      - asttokens==2.2.1
      - audioread==3.0.0
      - click==8.1.3
      - cmake==3.25.0
      - colorama==0.4.6
      - decorator==5.1.1
      - docker-pycreds==0.4.0
      - einops==0.6.1
      - executing==1.2.0
      - filelock==3.9.0
      - fsspec==2023.4.0
      - gitdb==4.0.10
      - gitpython==3.1.31
      - huggingface-hub==0.14.1
      - icecream==2.1.3
      - jinja2==3.1.2
      - joblib==1.2.0
      - lazy-loader==0.2
      - librosa==0.10.0.post2
      - lit==15.0.7
      - llvmlite==0.39.1
      - markupsafe==2.1.2
      - mpmath==1.2.1
      - msgpack==1.0.5
      - natsort==8.3.1
      - networkx==3.0
      - numba==0.56.4
      - numpy==1.23.5
      - omegaconf==2.3.0
      - pathtools==0.1.2
      - protobuf==4.22.3
      - psutil==5.9.5
      - pydub==0.25.1
      - pygments==2.15.1
      - pylint==2.17.4
      - pyqt5-sip==12.11.0
      - pyyaml==6.0
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - sentry-sdk==1.21.1
      - setproctitle==1.3.2
      - smmap==5.0.0
      - soundfile==0.12.1
      - soxr==0.3.5
      - sympy==1.11.1
      - threadpoolctl==3.1.0
      - timm==0.6.13
      - torch==2.0.0+cu118
      #- torch==2.0.0
      - torchaudio==2.0.1+cu118
      #- torchaudio==2.0.1
      - torchmetrics==0.11.4
      - torchvision==0.15.1+cu118
      #- torchvision==0.15.1
      - tqdm==4.65.0
      - typing-extensions==4.4.0
      - wandb==0.15.0
      - pydub
      - matplotlib
      - librosa
      - gitpython
      - pyyaml
